[package]
name = "nes_emulator"
version = "0.1.0"
authors = ["devtanc <devtanc@gmail.com>"]

[[bin]]
name = "nes_emulator"
path = "main.rs"

[dependencies]
tui = "0.5"
termion = "^1.5"
hex = "0.4.0"
failure = "0.1"
